export const images = {
  ic_aditya: "../assets/bank-logos/Aditya-Birla.png",
  ic_axis: "../assets/bank-logos/Axis-bank.png",
  ic_axisFinance: "../assets/bank-logos/Axis-Finance.png",
  ic_bajaj: "../assets/bank-logos/Bajaj.avif",
  ic_finnable: "../assets/bank-logos/Finnable.avif",
  ic_fullerton: "../assets/bank-logos/Fullerton.avif",
  ic_hdfc: "../assets/bank-logos/HDFC-B&W.png",
  ic_heroFin: "../assets/bank-logos/Hero-FinCorp.png",
  ic_icici: "../assets/bank-logos/ICICI.png",
  ic_idfc: "../assets/bank-logos/IDFC.png",
  ic_incred: "../assets/bank-logos/Incred.png",
  ic_indus: "../assets/bank-logos/IndusInd.jpg",
  ic_kotak: "../assets/bank-logos/Kotak-Bank.png",
  ic_poonawalla: "../assets/bank-logos/Poonawalla-Finance.jpg",
  ic_standardChartered: "../assets/bank-logos/Standard-chartered.png",
  ic_tata: "../assets/bank-logos/Tata-Capital.png",
  ic_ujjivan: "../assets/bank-logos/Ujjivan-small-finance-bank-.png",
  ic_yes: "../assets/bank-logos/Yes-bank.png",
};
